#!/usr/bin/env bash

#Set CapsLock to Ctrl key - Uncomment the following two lines for laptop:
# setxkbmap -option ""
# setxkbmap -option "ctrl:nocaps"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         2
bspc config focused_border_color '#E99000'
bspc config normal_border_color '#000000'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a copyq state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a "calendar-popup" state=floating
bspc rule -a Xzoom state=floating

#Wallpaper folder:
# feh --bg-fill -z $HOME/Documents/JV/Wallpapers/wallpapers/
#Wallpaper specific wallpaper
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0203.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0148.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0210.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0239.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0229.jpg
feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0232.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0233.jpg

# polybar theme:
$HOME/.config/polybar/blocks/launch.sh &

#Keyboard repeat rate:
xset r rate 300 50

# Uncomment for PC:
# pkill -x xautolock
# xautolock -detectsleep -time 10 -locker "i3lock -c 222222 -n" &

# Auto start programs
pgrep -x copyq > /dev/null || copyq &
pgrep -x autokey > /dev/null || autokey &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
