#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config border_width         2
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a copyq state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a "calendar-popup" state=floating
bspc rule -a Xzoom state=floating

#Wallpaper folder:
# feh --bg-fill -z $HOME/Documents/JV/Wallpapers/wallpapers/
#Wallpaper specific wallpaper
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0203.jpg
feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0148.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0210.jpg
# feh --bg-fill $HOME/Documents/JV/Wallpapers/wallpapers/0239.jpg

# polybar theme:
$HOME/.config/polybar/blocks/launch.sh &

#Keyboard repeat rate:
xset r rate 300 50

# Auto start programs
pgrep -x copyq > /dev/null || copyq &
pgrep -x autokey > /dev/null || autokey &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
